version: '3.8'
services:
  sonarqube:
    image: sonarqube:9.9.3-community
    container_name: ${SONARQUBE_CONTAINER_NAME}
    networks:
      - sonarnet
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://host.docker.internal:54321/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - ${SONARQUBE_DATA_VOLUME}:/opt/sonarqube/data
      - ${SONARQUBE_LOGS_VOLUME}:/opt/sonarqube/logs
      - ${SONARQUBE_EXTENSIONS_VOLUME}:/opt/sonarqube/extensions
    ports:
      - "19000:9000"
    depends_on:
      - sonarqube_postgres_db


  sonarqube_postgres_db:
    image: postgres:13
    container_name: sonarqube_postgres_db
    networks:
      - sonarnet
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - ${POSTGRES_IMAGE_VOLUME}:/var/lib/postgresql
      - ${POSTGRES_DATA_VOLUME}:/var/lib/postgresql/data
    ports:
      - "54321:5432"

networks:
  sonarnet:
    driver: bridge
