version: '3.8'
services:
  mongodb:
    image: mongo:7.0
    container_name: ${MONGODB_CONTAINER_NAME}
    networks:
      - mongodbnet
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
    volumes:
      - ${MONGODB_DATA_VOLUME}:/data/db
    ports:
      - "27017:27017"

networks:
  mongodbnet:
    driver: bridge